name: Build apps

on:
  [push, workflow_dispatch]

jobs:
  buildnw:
    name: Build NW.js apps
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v2

      - name: Create build directory
        run: mkdir build

      - name: Download Windows x64 NW.js
        run: wget https://dl.nwjs.io/v0.55.0/nwjs-v0.55.0-win-x64.zip

      - name: Download Windows ia32 NW.js
        run: wget https://dl.nwjs.io/v0.55.0/nwjs-v0.55.0-win-ia32.zip

      - name: Download Linux x64 NW.js
        run: wget https://dl.nwjs.io/v0.55.0/nwjs-v0.55.0-linux-x64.tar.gz

      - name: Download Linux ia32 NW.js
        run: wget https://dl.nwjs.io/v0.55.0/nwjs-v0.55.0-linux-ia32.tar.gz

      - name: Download MacOS NW.js
        run: wget https://dl.nwjs.io/v0.55.0/nwjs-v0.55.0-osx-x64.zip

      - name: Extract Windows x64 NW.js
        run: unzip nwjs-v0.55.0-win-x64.zip

      - name: Extract Windows ia32 NW.js
        run: unzip nwjs-v0.55.0-win-ia32.zip

      - name: Extract Linux x64 NW.js
        run: tar -xvf nwjs-v0.55.0-linux-x64.tar.gz

      - name: Extract Linux ia32 NW.js
        run: tar -xvf nwjs-v0.55.0-linux-ia32.tar.gz

      - name: Extract MacOS NW.js
        run: unzip nwjs-v0.55.0-osx-x64.zip

      - name: Delete archives
        run: rm nwjs-v0.55.0-linux-x64.tar.gz nwjs-v0.55.0-win-x64.zip nwjs-v0.55.0-linux-ia32.tar.gz nwjs-v0.55.0-win-ia32.zip nwjs-v0.55.0-osx-x64.zip

      - name: Rename and move NW.js directories
        run: mv nwjs-v0.55.0-linux-x64 build/ecowisdom-linux-x64 && mv nwjs-v0.55.0-win-x64 build/ecowisdom-win-x64 && mv nwjs-v0.55.0-linux-ia32 build/ecowisdom-linux-ia32 && mv nwjs-v0.55.0-win-ia32 build/ecowisdom-win-ia32 && mv nwjs-v0.55.0-osx-x64/nwjs.app build/Ecowisdom.app

      - name: Create package.nw directories
        run: mkdir build/ecowisdom-linux-x64/package.nw && mkdir build/ecowisdom-win-x64/package.nw && mkdir build/ecowisdom-linux-ia32/package.nw && mkdir build/ecowisdom-win-ia32/package.nw && mkdir build/Ecowisdom.app/Contents/Resources/app.nw

      - name: Install dependencies
        run: npm i
        
      - name: Copy files to NW.js directories
        run: cp -r $(ls | grep -v build) build/ecowisdom-linux-x64/package.nw && cp -r $(ls | grep -v build) build/ecowisdom-win-x64/package.nw && cp -r $(ls | grep -v build) build/ecowisdom-linux-ia32/package.nw && cp -r $(ls | grep -v build) build/ecowisdom-win-ia32/package.nw && cp -r $(ls | grep -v build) build/Ecowisdom.app/Contents/Resources/app.nw

      - name: Rename executables
        run: mv build/ecowisdom-linux-x64/nw build/ecowisdom-linux-x64/ecowisdom && mv build/ecowisdom-linux-ia32/nw build/ecowisdom-linux-ia32/ecowisdom && mv build/ecowisdom-win-x64/nw.exe build/ecowisdom-win-x64/ecowisdom.exe && mv build/ecowisdom-win-ia32/nw.exe build/ecowisdom-win-ia32/ecowisdom.exe

      - name: Create Debian installer file structure
        run: mkdir build/ecowisdom-debian-x64 && mkdir build/ecowisdom-debian-x64/usr && mkdir mkdir build/ecowisdom-debian-x64/DEBIAN && mkdir build/ecowisdom-debian-x64/usr/bin && mkdir build/ecowisdom-debian-x64/usr/lib && mkdir build/ecowisdom-debian-x64/usr/share && mkdir build/ecowisdom-debian-x64/usr/share/applications

      - name: Copy Linux build to Debian installer
        run: cp -r build/ecowisdom-linux-x64 build/ecowisdom-debian-x64/usr/lib

      - name: Create Symlink to command
        run: cd build/ecowisdom-debian-x64/usr/bin && ln -s ../lib/ecowisdom-linux-x64/ecowisdom

      - name: Copy control file
        run: cp DEBIAN/control build/ecowisdom-debian-x64/DEBIAN

      - name: Copy desktop file
        run: cp ecowisdom.desktop build/ecowisdom-debian-x64/usr/share/applications

      - name: Create Debian installer
        run: cd build && dpkg-deb --build ecowisdom-debian-x64

      - name: Create Windows archives
        run: cd build && zip -r ecowisdom-win-x64.zip ecowisdom-win-x64 && zip -r ecowisdom-win-ia32.zip ecowisdom-win-ia32

      - name: Create Linux archives
        run: cd build && tar -czvf ecowisdom-linux-x64.tar.gz ecowisdom-linux-x64 && tar -czvf ecowisdom-linux-ia32.tar.gz ecowisdom-linux-ia32

      - name: Create MacOS archive
        run: cd build && zip -r ecowisdom-osx.zip Ecowisdom.app

      - name: Upload Windows x64 build
        uses: actions/upload-artifact@v2
        with:
          name: ecowisdom-win-x64.zip
          path: build/ecowisdom-win-x64.zip

      - name: Upload Linux x64 build
        uses: actions/upload-artifact@v2
        with:
          name: ecowisdom-linux-x64.tar.gz
          path: build/ecowisdom-linux-x64.tar.gz

      - name: Upload Windows ia32 build
        uses: actions/upload-artifact@v2
        with:
          name: ecowisdom-win-ia32.zip
          path: build/ecowisdom-win-ia32.zip

      - name: Upload Linux ia32 build
        uses: actions/upload-artifact@v2
        with:
          name: ecowisdom-linux-ia32.tar.gz
          path: build/ecowisdom-linux-ia32.tar.gz

      - name: Upload Debian installer build
        uses: actions/upload-artifact@v2
        with:
          name: ecowisdom-debian-x64.deb
          path: build/ecowisdom-debian-x64.deb

      - name: Upload MacOS build
        uses: actions/upload-artifact@v2
        with:
          name: ecowisdom-osx.zip
          path: build/ecowisdom-osx.zip
